repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-yaml
        args: ["--unsafe"]
  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: local
    hooks:
      - id: system
        name: format
        entry: make format
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: check
        entry: make check
        pass_filenames: false
        language: system
        stages: [push]
